name: Build
on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment Variables
        run: |
          IMG=lavalink
          OWNER="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
          echo "IMG=${IMG}" >> $GITHUB_ENV
          echo "IMAGE=ghcr.io/${OWNER}/${IMG}" >> $GITHUB_ENV
          echo "VERSION=$GITHUB_REF_NAME" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Java v17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download & Repack Lavalink.jar
        run: |
          wget https://github.com/freyacodes/Lavalink/releases/download/${{ env.VERSION }}/Lavalink.jar
          wget https://github.com/aikaterna/lavaplayer-natives/raw/master/linux-aarch64/libconnector.so
          mkdir -p Lavalink-patch/lavaplayer-natives-patch; pushd Lavalink-patch
          unzip ../Lavalink.jar
          pushd lavaplayer-natives-patch
          unzip ../BOOT-INF/lib/lavaplayer-natives*.jar
          mkdir -p natives/linux-aarch64/
          cp ../../libconnector.so natives/linux-aarch64
          jar -cvfm ../BOOT-INF/lib/lavaplayer-natives*.jar META-INF/MANIFEST.MF .
          popd; rm -rf lavaplayer-natives-patch
          jar -cvf0m ../LavalinkPatch.jar META-INF/MANIFEST.MF .
          popd; rm -rf Lavalink-patch

      - name: Release LavalinkPatch.jar
        uses: softprops/action-gh-release@v1
        with:
          files: LavalinkPatch.jar

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.IMAGE }}:${{ env.VERSION }}
            ${{ env.IMAGE }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
